# пример конфига
debug: true
basePath: "big-sister-parser"
host: "http://localhost:3000/"

db:
  debug: true
  host: "host"
  port: 5432
  username: "admin"
  password: "admin"
  database: "big-sister-parser"
  
grpc:
  url: "localhost:50051"
  package: 'arango'
  protoPath: '../src/proto/arango.proto'


arango: {
  url: 'http://localhost:8529',  
  database: 'big-sister-parser',
  username: 'root',
  password: 'test',
}

vkApi:
  baseUrl: "https://api.vk.com/method"
  version: "5.131"

