# пример конфига
debug: true
envSecret: "dev-insecure-secret-key-32bytes!"

enableThrift: false
basePath: "big-sister-parser"
host: "http://localhost:3000/"

db:
  debug: true
  host: "host"
  port: 5432
  username: "admin"
  password: "admin"
  database: "big-sister-parser"

arango: {
  url: 'http://localhost:8529',  
  database: 'big-sister-parser',
  username: 'root',
  password: 'test',
}

redis: {
  url: "redis://127.0.0.1:6379"
}

vkApi:
  baseUrl: "https://api.vk.com/method"
  version: "5.131"

token: 
  vkDefault: "vk1.a.abcdef123456..."