# мой конфиг settings.prod.yml
debug: false
envSecret: "prod-insecure-secret-key-32bytes!"

basePath: "big-sister-parser"
host: "http://localhost:3002/"
enableThrift: true

db:
  debug: true
  host: "host.docker.internal"
  port: 5432
  username: "postgres"
  password: "admin"
  database: "big-sister"

arango:
  url: "http://host.docker.internal:8529"
  database: "bs"
  username: "root"
  password: "test"

redis:
  url: "redis://host.docker.internal:6379"

vkApi:
  baseUrl: "https://api.vk.com/method"
  version: "5.131"

token: 
  vkDefault: "vk1.a.fEjt5bznMF-MZxX3..."

