# пример конфига
debug: true
basePath: "big-sister-parser"
host: "TODO"

# БД.
db:
  debug: true
  host: "host"
  port: 5432
  username: "admin"
  password: "admin"
  database: "big-sister-parser-v1"
  
grpc:
  url: "http://127.0.0.1:8529"
  database: "_system"
  username: "root"
  password: "test"
  package: 'arango'
  protoPath: '../proto/arango.proto'
   


